### PR TITLE
Export `Props` type as `ReactSlidingPaneProps`

### PR DESCRIPTION
**Pull request by athrunsun**
I need to create wrapper components for `ReactSlidingPane` thus I need to access its props type .

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Hey @athrunsun ! I do not mind the change, but there is built-in type helper that allows to extract props types from component — `type Props = React.ComponentProps<typeof ReactSlidingPane>;`
image

**Comment by athrunsun** [comment]
@DimitryDushkin Can you take a look at this please? Generated type definition doesn't take effect because it is not included in `package.json`.

**Comment by DimitryDushkin** [comment]
@athrunsun hey! Thank you for this PR and your arguments. Totally reasonable. I'm merging it and preparing a new release.

**Comment by athrunsun** [comment]
@DimitryDushkin Thank you! Looking forward to the new release!

**Comment by DimitryDushkin** [comment]
> @DimitryDushkin Thank you! Looking forward to the new release!

It's live :)

**Pull request merged**
